### ISSUE TITLE
Setting Cookie Path

### ISSUE THREAD

**Issue by aaronleopold** [Aurora2500/rocket-session-store#1]
Hey there, love the library! I was wondering if there was a way to control how the cookie is formed in SessionStoreFairing? I was hoping to be able to set the path of the cookie, rather than it defaulting to the current path. Maybe by adding some optional `cookie` config to the store? Thanks for the awesome library 🙂

**Comment by Aurora2500** [comment]
There isn't yet, but if you manage to make something that works I'd gladly accept PRs!

Gonna make the repo a bit more organized for accepting PRs right now. Thanks for using my project!

**Comment by aaronleopold** [comment]
Sure! I can clean up what I've done on a fork and throw together a quick PR after work. Thanks for the reply!

**Comment by Aurora2500** [comment]
Closed by #2
